### PR TITLE
[WIP] Unittests

### PR DESCRIPTION
**Pull request by jetuk**
This is WIP fixing up the unittests. 

I have been running these with pytest. It has merged previous commits from #1.

I'll update as things progress.

### CODE REVIEW

**Comment by jetuk** [comment]
@knoxsp any comments on this?

1. Refactoring tests to use `pytest` instead of `nose`.
2. CI failures due to the hardcoded config file.

**Comment by knoxsp** [comment]
@jetuk 
 1. Does travis require pytest over nose? What is the difference between the two from an implementation point of view?
 2. Can you explain what hardcoding is happening? How might we solve it?

**Comment by jetuk** [comment]
No travis doesn't require pytest. Pytest can run standard unittests, but I think has better assertion readability (it does some clever introspection as to why the assert failed) and the `@pytest.fixture` feature is pretty cool. At least I think it is easier and quicker than set up and tear down functions. 

See test report on travis here for Python 3.6
https://travis-ci.org/hydraplatform/hydra-base/jobs/318303647

```
==================================== ERRORS ====================================

_____________________ ERROR collecting tests/test_users.py _____________________

tests/test_users.py:1: in <module>

    import hydra_base

hydra_base/__init__.py:28: in <module>

    from .lib.data import *

hydra_base/lib/data.py:49: in <module>

    from . import units as hydra_units

hydra_base/lib/units.py:466: in <module>

    hydra_units = Units()

hydra_base/lib/units.py:68: in __init__

    open(user_unitfile, 'a').close()

E   FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/Dropbox/git/hydra-base/hydra_base/static/user_units.xml'

!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!

=========================== 1 error in 1.30 seconds ============================
```

**Comment by knoxsp** [comment]
The error looks to me like it's a config issue in hydra.ini -- the config file is set to my local path, so we just need to update 'hydra_base_dir' in hydra.ini to something travis-friendly.

**Comment by jetuk** [comment]
Yeah I am not sure how the default for this should be set? I had to change it locally which is not ideal. I guess it should be a relative path by default?

**Pull request closed without merging**
